### ISSUE TITLE
Align function/coding conventions

### ISSUE THREAD

**Issue by edelarua** [pharmaverse/falcon#108]
This issue is created to discuss and align conventions used when creating functions within the repo. 

Example topics of discussion:

- Should we ever hard-code variable names? If so, which ones?
- Should all table functions have the same options available (`annotations`, `prune_0`, etc.)? If so, should we add any more standard options?
- Should option to choose which statistics are included in Table 2 be removed to align with other tables (which have statistics hard-coded)?

Feel free to discuss the above questions and any others relating to coding convention in the comments below. Thanks!

**Comment by jknizia** [comment]
Thanks for creating the issue! Here are additional topics I've been thinking about, more directed to our internal workflow:

- Should we establish minimum requirements on approving a PR?
- Should we align on how to call functions from other packages? (Explicit via ::: vs. implicit.) Should we discuss style at all?

**Comment by aassuied-ps** [comment]
Thank you! Here's a new one:

- Should we have common argument names for some arguments (for example, the dataset to load for the tables, in table 5 it's called `df`, for table 6 it's called `adae`)?

**Comment by edelarua** [comment]
Closing this issue as discussion points have been addressed.
