### ISSUE TITLE
Table 21 updates

### ISSUE THREAD

**Issue by aassuied-ps** [pharmaverse/falcon#122]
Link to the template: https://pharmaverse.github.io/falcon/quarto/table-templates/template-table_21.html

- [x] 1. `lbl_overall` argument is missing. It was initially implemented but bugged due to percentages above 100% in the overall column on default data.
- [x] 2. Picture on the quarto site is not displayed: change `table_21.PNG` into `table_21.png` in `quarto/assets/images/screenshots/`.
- [x] 3. Add `- quarto/table-templates/template-table_21.qmd` in `_quarto.yml` (line 94).
- [x] 4. Create `tests/testthat/test-table_21.R`.

**Comment by aassuied-ps** [comment]
> Thanks Alex! I included some of these fixes in #116, so only the first item still needs to be addressed: 2 & 3. [828e098](https://github.com/pharmaverse/falcon/commit/828e098155be4e6858c9f9d01b3255fd91eebe93) 4. [07e8385](https://github.com/pharmaverse/falcon/commit/07e8385c9f1150b8afc111b9e53766b25735d953)

Hi @edelarua, thank you very much! My branch is merged now but I don't see the modifications you made on points 2, 3 and 4. Did I miss something?

**Comment by edelarua** [comment]
Thanks @aassuied-ps! #116 where the changes are hasn't been reviewed/merged in yet but the changes will appear once that PR is in so it's fine to close this issue.
