### ISSUE TITLE
falcon branding/website discussion

### ISSUE THREAD

**Issue by telepath37** [pharmaverse/falcon#29]
can use a similar layout as https://insightsengineering.github.io/tlg-catalog/ 

@edelarua @ayogasekaram we'd like to set up a quarto page simlar to TLG-C for falcon. I can add more details later regarding designs, outlines, goals, but please comment from technical side regarding feasibility/challenges/complexity, assuming we first release 10 TLG templates according to the FDA guidance.

**Comment by edelarua** [comment]
@telepath37 I think this is a great idea for improving structure/readability. I helped with setting up/formatting the quarto site for TLG-C and it wasn't too difficult to implement, so I don't anticipate any issues using it here as well. `qmd` files are very similar to `Rmd` files, so anyone familiar with those shouldn't have any problems adapting to the change.

**Comment by freestatman** [comment]
Product Requirements (Quarto Website) discussed at the team meeting on 2023-04-18: 

1.	The objective is to put the falcon R template side-by-side with FDA guidance output
       -	Adding FDA table screenshot 
2.	Have "Get started" and “About” page: packages installation guide, mock data, our collaboration story, FAQ
3.	Add placeholder section for talks and presentations
4.	Build a website (more than a technical document). Incorporate an exciting/interactive landing page, while ensuring that the overall quarto site does not have a uniform appearance. For inspiration, consider examples such as those found at https://quarto.org/docs/gallery/ and https://nbdev.fast.ai/.
       -	Create a branding
5.	Create FDA Guidance meta data
       -	Convert pdf/word guidance document into a programming accessible meta data format, e.g., json or csv. 
       -	Transform a guidance document that currently exists in pdf/word format into quarto format 
       -	This process could be reused for pharma’s internal need. Selling point: you can do the same with your legacy document in your own organization.

**Comment by edelarua** [comment]
Closing with related issues linked below (corresponding to 1-5 listed above):
1. #40
2. #37
#38
#39
3. #44 
4. #36, #45
5. #41
