### ISSUE TITLE
Create a logo/hex sticker for falcon

### ISSUE THREAD

**Issue by telepath37** [pharmaverse/falcon#36]
to be used in the quarto website and all external communications

See some examples from other pharmaverse packages [here](https://posit.co/blog/pharmaverse-packages-for-clinical-reporting-workflows/)

**Comment by jknizia** [comment]
A first thought: We could think about putting an approaching falcon on the sticker. I, personally, like those geometric concepts, similar to the one I attached (but maybe less origami style). 

We should also discuss the color theme. In my opinion, the colors for the hex sticker and the prominent colors we will use for the quarto page should look harmonic. 

![image](https://user-images.githubusercontent.com/85986258/234218272-d8561aa0-a749-4ebe-a6b9-cee7eda64384.png)

**Comment by mattkorb** [comment]
![falcon](https://user-images.githubusercontent.com/123395522/235637878-8da4eeba-51b2-4b49-99dd-272d798dd3d3.png)
How about a green color theme?
Like a forest the falcon lives in.

**Comment by jknizia** [comment]
Here's a more complete proposal. More to come :-)

![Image](https://github.com/pharmaverse/falcon/assets/85986258/626c3b9e-5e11-4578-b10f-3c2254f582e8)

**Comment by freestatman** [comment]
I like this more complete falcon, and it kind of relates to the style of {admiral} logo, another cross company collaberation package.

**Comment by jknizia** [comment]
Hi @edelarua, here is the logo according to your requests in three different sizes :-)
![falcon2](https://github.com/pharmaverse/falcon/assets/85986258/8d4b83c9-c071-4795-bb44-e4a479bb60dd)
![falcon2-extrasmall](https://github.com/pharmaverse/falcon/assets/85986258/cfb6d224-a7c7-4cf4-8e11-4debf638ed00)
![falcon2-small](https://github.com/pharmaverse/falcon/assets/85986258/31291077-b626-41d3-af54-ca8494892471)
