### ISSUE TITLE
Minor website enhancements

### ISSUE THREAD

**Issue by edelarua** [pharmaverse/falcon#81]
- Add PHUSE EU to "Upcoming" section
- Update flip cards with names
- Update FAQ placeholder
- Fix screenshot file paths on Getting Started page
- Check spelling/grammar in all files

**Comment by aassuied-ps** [comment]
The problem related to the screenshot paths on the getting started page should be same as mentionned in issue https://github.com/pharmaverse/falcon/issues/83

**Comment by edelarua** [comment]
> The problem related to the screenshot paths on the getting started page should be same as mentionned in issue #83

Thanks @aassuied-ps! I have converted all the file extensions to lowercase which should solve the issue.

**Comment by aassuied-ps** [comment]
Can we add the following to this issue or should I open a new issue?

The "Our Collaboration Journey" button on the homepage does lead to this page: https://pharmaverse.github.io/quarto/about.html#our-collaboration-journey
Which is not active.

I think it should lead to this link: 
https://pharmaverse.github.io/falcon/quarto/about.html#our-collaboration-journey

**Comment by edelarua** [comment]
@aassuied-ps I have added a fix for this link to the PR. Thanks!
