### ISSUE TITLE
Spec. Screenshot is not working for table 5 template

### ISSUE THREAD

**Issue by aassuied-ps** [pharmaverse/falcon#83]
![image](https://github.com/pharmaverse/falcon/assets/123543888/7e3c7457-f4e3-4a02-8a39-ce0e8a32b651)

I think the issue is on line 10 of [template-table_05.qmd](https://github.com/pharmaverse/falcon/blob/main/quarto/table-templates/template-table_05.qmd):

`![](../assets/images/screenshots/table_05.png){fig-align="center"}`

![image](https://github.com/pharmaverse/falcon/assets/123543888/dbca5a60-64b8-4332-a394-ef50a5883aed)

Update the screenshot name with lowcase `.png` should be enough to correct it.

**Comment by edelarua** [comment]
Closed by https://github.com/pharmaverse/falcon/pull/82.
