### ISSUE TITLE
Invalid publishing date on template library

### ISSUE THREAD

**Issue by aassuied-ps** [pharmaverse/falcon#91]
It seems an invalidated date appears on the [Template Library Index](https://pharmaverse.github.io/falcon/quarto/index-templates.html) page

![image](https://github.com/pharmaverse/falcon/assets/123543888/6c3c396d-5c5d-4ec8-860a-947fc108b426)

This is not reported on the other pages. I think it's done here in [index-template.qmd](https://github.com/pharmaverse/falcon/blob/main/quarto/index-templates.qmd) on line 3:

```
title: Template Library Index
date: '`r Sys.Date()`'
```

I can delete this part if you agree

**Comment by edelarua** [comment]
I noticed that too. You can go ahead and delete it. Thanks!
