### ISSUE TITLE
Table 21 -  Overview of Serious Adverse Events by Demographic Subgroup

### ISSUE THREAD

**Issue by aassuied-ps** [pharmaverse/falcon#95]
## Table Layout & Design

![Screenshot 2023-08-08 155601](https://github.com/pharmaverse/falcon/assets/59304861/01cd0edc-9bc4-420b-a7aa-1bdddbf7342a)

Please refer to the pdf here for more details: [FDA-2022-N-1961-0002_attachment_1.pdf](https://github.com/pharmaverse/falcon/files/10744259/FDA-2022-N-1961-0002_attachment_1.pdf)
Can also be used for tables 22 and 23.

## Description

Overview of SAE, by subgroups, Safety Population, Pooled Analysis or Trial X

## Analysis Datasets

Any dataset - df
**ADSL**
**ADAE**

When using data from the `scda` package, please use datasets with `archive_name` set to `"rcd_2022_10_13"`.

## Analysis Filtering

![table21](https://github.com/pharmaverse/falcon/assets/123543888/3777733a-89b0-4587-b119-ef049c633f6a)

## Column Variable

**ARM**

## Additional Notes

N/A

**Comment by aassuied-ps** [comment]
Add a check on `AESER` maybe.

`df_explicit_na()` and `alt_counts_df()` are not used due to issues with the denominator in case of missing data. Maybe I'm missing something.

**Comment by aassuied-ps** [comment]
Hi @edelarua,
I think the current denominator is the number of participant with a value (F/M) in the variable, not the participants with an adverse event. For the variable `SEX`, the denominator is 134 in group A and corresponds to 79+55 (see table 2 template), while there are 104 participants with a SAE in this group. Or maybe I misunderstood your message?

Still you are right, maybe the denominator should be the number of participant in each category as you mention (number of female patients with adverse events / total number of female patients).

The footnote says  _"Ns, total number of patients for each specific subgroup"_ and the text above the table says  _"Documenting findings of safety by demographic subgroups (sex, age, race, and ethnicity)"_ so I considered each variable as a subgroup, not each modalities as a subgroup. 
But I'm wrong perhaps. Did you already compute tables like this? I'm gonna ask some people on my side also.


![image](https://github.com/pharmaverse/falcon/assets/123543888/eafdf68a-2a21-42be-9de3-3daaf1407b60)

![image](https://github.com/pharmaverse/falcon/assets/123543888/7762ec90-88d4-49d5-96a6-83c8ae0cb424)

**Comment by edelarua** [comment]
Hi @aassuied-ps,
We don't typically use this denominator in our functions in `tern`, so we can work on creating a custom analysis function for this table. It shouldn't be too difficult since it will be very similar to `s_count_occurrences`. If you can confirm what the denominator should be that would be great! (though I think you're right that it's using the subcategory for each specific row)

**Comment by edelarua** [comment]
Hi @aassuied-ps,

I have added in a custom analysis function (`a_count_occurrences_ser_ae`) that accomplishes what I think we want in this table - it can be tweaked if anything else/further customization is needed. It has an option to specify the denominator used, and I have added in a `N_s` option.  We will likely add this as an option within `tern` at some point, but for now we can use this custom function which is derived from `tern:::s_count_occurrences`.  The current 3 denominator options are as follows, where the denominator is circled in red for each of the cells highlighted in yellow:

![table_21 calculations](https://github.com/pharmaverse/falcon/assets/59304861/eb6d9df7-5b9f-447e-a04a-6ac09d4cd7f5)

1. `N_col` takes the column total as denominator.
2. `n` takes the total number of serious AEs in the column as denominator.
3. `N_s` takes the total number of records in the current row/column context (regardless of AEs) - these denominators are also the numbers that appear when output is created via `make_table_02`.

If 3 is incorrect or we need other options please let me know or feel free to further customize the function yourself!

Thanks!! :)

**Comment by aassuied-ps** [comment]
Hi @edelarua,

Thank you very much again for this. It's working great except for one thing : it's not working when we want to display an overall column. I'm trying to figure out why.

```
# N_s without a overall column
z1 <- make_table_21(df = df, alt_counts_df = adsl, denom="N_s")
z1

# N_col with an overall column
z2 <- make_table_21(df = df, alt_counts_df = adsl, denom="N_col", lbl_overall = "lbl1")
z2

# N_s with an overall column
z3 <- make_table_21(df = df, alt_counts_df = adsl, denom="N_s", lbl_overall = "lbl2")
```

```
Error in assert_proportion_value(x[2], include_boundaries = TRUE) : 
  Assertion on 'x' failed: Element 1 is not <= 1
```

**Comment by edelarua** [comment]
Hi @aassuied-ps,

Yes, we should probably remove the `lbl_overall` argument. The error occurs because in the "overall" column when `N_s` is used as the denominator the percentage value is sometimes greater than 100%. Since it's not a requirement for the table we can remove it with no issues.
